import { expect, test } from '@playwright/test'

test('one bubble hands off without reopening delay and keeps author slots reactive', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => {
    if (message.type() === 'error' || /hydration/i.test(message.text())) {
      errors.push(message.text())
    }
  })
  await page.goto('/shared-tooltip')
  await expect(page.getByTestId('shared-tooltip-page')).toHaveAttribute('data-ready', 'true')
  const a = page.getByTestId('tooltip-trigger-a')
  const b = page.getByTestId('tooltip-trigger-b')
  const bubble = page.getByTestId('shared-bubble')
  await a.dispatchEvent('mouseenter')
  await page.waitForTimeout(100)
  await expect(bubble).toHaveCount(0)
  await expect(bubble).toContainText('Alpha content')
  const original = await bubble.elementHandle()
  const firstPosition = await bubble.boundingBox()
  await a.dispatchEvent('mouseleave')
  await b.dispatchEvent('mouseenter')
  await expect(bubble).toContainText('Beta content', { timeout: 200 })
  expect(await bubble.evaluate((element, previous) => element === previous, original)).toBe(true)
  await expect(page.locator('.tooltip')).toHaveCount(1)
  await expect(bubble).toContainText('Author context preserved')
  await expect(page.getByTestId('tooltip-models')).toHaveText('false/true')
  await expect.poll(async () => (await bubble.boundingBox()).x).toBeGreaterThan(firstPosition.x + 50)
  // Wait beyond A's closing timer: it must not dismiss B.
  await page.waitForTimeout(350)
  await expect(bubble).toBeVisible()
  await page.getByRole('button', { name: 'Update content' }).click()
  await expect(bubble).toContainText('Updated Beta')
  const beforeRetarget = await bubble.boundingBox()
  await page.getByRole('button', { name: 'Move Beta target' }).click()
  await expect(page.getByTestId('tooltip-models')).toHaveText('false/true')
  expect(await bubble.evaluate((element, previous) => element === previous, original)).toBe(true)
  await expect.poll(async () => Math.abs((await bubble.boundingBox()).x - beforeRetarget.x)).toBeGreaterThan(50)
  await b.dispatchEvent('mouseleave')
  await page.waitForTimeout(350)
  await expect(bubble).toBeVisible()
  await page.getByTestId('alternate-target').dispatchEvent('mouseleave')
  await page.waitForTimeout(100)
  await expect(bubble).toBeVisible()
  await expect(bubble).toHaveCount(0)
  await page.getByRole('button', { name: 'Reset Beta target' }).click()

  await page.getByRole('button', { name: 'Toggle manual' }).click()
  await page.getByRole('button', { name: 'Open Alpha' }).click()
  await expect(bubble).toContainText('Alpha content')
  await page.getByRole('button', { name: 'Open Beta' }).click()
  await expect(bubble).toContainText('Updated Beta')
  await expect(page.getByTestId('tooltip-models')).toHaveText('false/true')
  await page.getByRole('button', { name: 'Close Beta' }).click()
  await expect(bubble).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle manual' }).click()
  await a.dispatchEvent('mouseenter')
  await page.getByRole('button', { name: 'Toggle declarations' }).click()
  await page.waitForTimeout(450)
  await expect(bubble).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle declarations' }).click()
  await b.dispatchEvent('mouseenter')
  await expect(bubble).toContainText('Updated Beta')
  await page.getByRole('button', { name: 'Toggle declarations' }).click()
  await expect(bubble).toHaveCount(0)
  expect(errors).toEqual([])
})
