import { expect, test } from '@playwright/test'

test('DurationInput preserves milliseconds, scoped slots and public input methods', async ({ page }) => {
  const problems = []
  page.on('pageerror', error => problems.push(error.message))
  page.on('console', message => {
    if (/hydration|no active component/i.test(message.text())) {
      problems.push(message.text())
    }
  })
  await page.goto('/cs-CZ/vapor-duration-input')
  await expect(page.getByTestId('duration-input-example')).toHaveAttribute('data-ready', 'true')
  const field = page.getByTestId('duration-input-field')
  const input = field.locator('input')
  await expect(input).toHaveValue('2')
  await expect(input).toHaveAttribute('placeholder', 'Duration value')
  await expect(field).toContainText('Duration')
  await page.getByRole('button', { name: 'Select input', exact: true }).click()
  await expect(input).toBeFocused()
  expect(await input.evaluate(el => [el.selectionStart, el.selectionEnd])).toEqual([0, 1])
  await expect(page.getByTestId('duration-events')).toHaveText('1/0')
  await page.getByRole('button', { name: 'Blur input', exact: true }).click()
  await expect(input).not.toBeFocused()
  await expect(page.getByTestId('duration-events')).toHaveText('1/1')
  await page.getByRole('button', { name: 'Read touched', exact: true }).click()
  await expect(page.getByTestId('duration-touched')).toHaveText('true')

  await field.getByRole('button', { name: /hodin/ }).click()
  await page.getByRole('button', { name: 'Minut', exact: true }).click()
  await expect(input).toHaveValue('120')
  await expect(page.getByTestId('duration-value')).toHaveText('7200000')
  await input.fill('90')
  await expect(page.getByTestId('duration-value')).toHaveText('5400000')
  await page.getByRole('button', { name: 'Toggle slots', exact: true }).click()
  await expect(page.getByTestId('duration-label')).toHaveText('Custom Duration')
  await field.getByRole('button', { name: 'Slot focus', exact: true }).click()
  await expect(input).toBeFocused()
  await field.getByRole('button', { name: 'Slot clear', exact: true }).click()
  await expect(input).toHaveValue('')
  await expect(page.getByTestId('duration-value')).toHaveText('empty')
  await field.getByRole('button', { name: /minut/ }).click()
  await page.getByRole('button', { name: 'Hodin', exact: true }).click()
  await expect(input).toHaveValue('')
  await expect(page.getByTestId('duration-value')).toHaveText('empty')
  await input.fill('3')
  await expect(page.getByTestId('duration-value')).toHaveText('10800000')
  await page.getByRole('button', { name: 'Toggle slots', exact: true }).click()
  await expect(page.getByTestId('duration-label')).toHaveCount(0)
  await expect(field).toContainText('Duration')
  await expect(field.getByRole('button', { name: 'Slot clear', exact: true })).toHaveCount(0)
  await expect(field.getByRole('button', { name: /hodin/ })).toBeVisible()
  await page.getByRole('button', { name: 'Toggle readonly', exact: true }).click()
  await expect(input).toHaveAttribute('readonly', '')
  await expect(field.getByRole('button')).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle readonly', exact: true }).click()
  await page.getByRole('button', { name: 'Toggle input owner', exact: true }).click()
  await expect(input).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle input owner', exact: true }).click()
  await page.getByRole('button', { name: 'Focus input', exact: true }).click()
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('3')
  expect(problems).toEqual([])
})

test('DurationInput renders its default label and units in SSR with localized navigation', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, javaScriptEnabled: false })
  try {
    const page = await context.newPage()
    await page.goto('/cs-CZ/vapor-duration-input')
    const field = page.getByTestId('duration-input-field')
    await expect(field.locator('input')).toHaveValue('2')
    await expect(field.locator('input')).toHaveAttribute('placeholder', 'Duration value')
    await expect(field).toContainText('Duration')
    await expect(field.getByRole('button', { name: /hodin/ })).toBeVisible()
    await expect(page.getByRole('link', { name: 'DurationInput · jednotky a sloty', exact: true }))
      .toHaveAttribute('href', '/cs-CZ/vapor-duration-input')
  } finally {
    await context.close()
  }
})
