import { expect, test } from '@playwright/test'

test('SearchInput synchronizes external models and restores slot fallbacks', async ({ page }) => {
  const problems = []
  page.on('pageerror', error => problems.push(error.message))
  page.on('console', message => {
    if (/hydration|no active component/i.test(message.text())) {
      problems.push(message.text())
    }
  })
  await page.goto('/cs-CZ/vapor-search-input')
  await expect(page.getByTestId('search-input-example')).toHaveAttribute('data-ready', 'true')
  const field = page.getByTestId('search-input-field')
  const input = field.locator('input')
  const icon = field.locator('[i-carbon\\:search]')
  await expect(input).toHaveValue('Alpha')
  await expect(icon).toBeVisible()
  await expect(input).toHaveAttribute('placeholder', 'Search value')
  await expect(input).toHaveAttribute('name', '_search')
  await page.getByRole('button', { name: 'Replace model', exact: true }).click()
  await expect(input).toHaveValue('Parent value')
  await expect(page.getByTestId('search-updates')).toHaveText('0')
  await page.getByRole('button', { name: 'Select input', exact: true }).click()
  await expect(input).toBeFocused()
  expect(await input.evaluate(el => [el.selectionStart, el.selectionEnd])).toEqual([0, 12])
  await expect(page.getByText('Default search help', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Blur input', exact: true }).click()
  await expect(input).not.toBeFocused()
  await expect(page.getByText('Default search help', { exact: true })).not.toBeVisible()
  await input.fill('Beta')
  await expect(page.getByTestId('search-value')).toHaveText('Beta')
  await expect(page.getByTestId('search-updates')).toHaveText('1')
  await input.press('Enter')
  await expect(page.getByTestId('search-enters')).toHaveText('1')
  await page.getByRole('button', { name: 'Toggle slots', exact: true }).click()
  await expect(icon).toHaveCount(0)
  await field.getByRole('button', { name: 'Slot focus', exact: true }).click()
  await expect(input).toBeFocused()
  await expect(page.getByText('Custom search help', { exact: true })).toBeVisible()
  await field.getByRole('button', { name: 'Slot clear', exact: true }).click()
  await expect(input).toHaveValue('')
  await expect(page.getByTestId('search-updates')).toHaveText('2')
  await expect(page.getByTestId('search-clears')).toHaveText('1')
  await page.getByRole('button', { name: 'Toggle slots', exact: true }).click()
  await expect(icon).toBeVisible()
  await page.getByRole('button', { name: 'Focus input', exact: true }).click()
  await expect(page.getByText('Default search help', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Replace model', exact: true }).click()
  await expect(input).toHaveValue('Parent value')
  await page.getByRole('button', { name: 'Clear input', exact: true }).click()
  await expect(input).toHaveValue('')
  await expect(input).not.toBeFocused()
  await expect(page.getByTestId('search-clears')).toHaveText('2')
  await page.getByRole('button', { name: 'Replace model', exact: true }).click()
  await page.getByRole('button', { name: 'Toggle input owner', exact: true }).click()
  await expect(input).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle input owner', exact: true }).click()
  await page.getByRole('button', { name: 'Focus input', exact: true }).click()
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('Parent value')
  expect(problems).toEqual([])
})

test('SearchInput renders its fallback icon and attrs in SSR with localized navigation', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, javaScriptEnabled: false })
  try {
    const page = await context.newPage()
    await page.goto('/cs-CZ/vapor-search-input')
    const field = page.getByTestId('search-input-field')
    await expect(field.locator('input')).toHaveValue('Alpha')
    await expect(field.locator('input')).toHaveAttribute('placeholder', 'Search value')
    await expect(field.locator('[i-carbon\\:search]')).toBeVisible()
    await expect(page.getByRole('link', { name: 'SearchInput · model a sloty', exact: true }))
      .toHaveAttribute('href', '/cs-CZ/vapor-search-input')
  } finally {
    await context.close()
  }
})
