import { expect, test } from '@playwright/test'

test('action primitives preserve events, models, DOM properties and remount', async ({ page }) => {
  const problems = []
  page.on('pageerror', error => problems.push(error.message))
  page.on('console', message => {
    if (/hydration|no active component/i.test(message.text())) {
      problems.push(message.text())
    }
  })

  await page.goto('/cs-CZ/vapor-action-primitives')
  await expect(page.getByTestId('action-primitives-example')).toHaveAttribute('data-ready', 'true')
  const drawerPanel = page.getByTestId('action-drawer-panel')
  await expect(drawerPanel).toHaveClass(/is-open/)
  await expect(page.getByTestId('action-drawer-panel-content')).toHaveText('Drawer content')
  await drawerPanel.locator('.drawer-title').getByRole('button').click()
  await expect.poll(() => drawerPanel.evaluate(element => element.classList.contains('is-open'))).toBe(false)

  const draggableContainer = page.getByTestId('action-draggable-container')
  await expect(page.getByTestId('draggable-container-item-0')).toHaveText('First draggable')
  await expect(page.getByTestId('draggable-container-item-1')).toHaveText('Second draggable')
  await draggableContainer.evaluate(element => element.moveItem(0, 1))
  await expect(page.getByTestId('draggable-container-item-0')).toHaveText('Second draggable')
  await draggableContainer.evaluate(element => element.disableDrop())
  await expect.poll(() => draggableContainer.evaluate(element => element.classList.contains('no-drop'))).toBe(true)
  await draggableContainer.evaluate(element => element.enableDrop())
  await expect.poll(() => draggableContainer.evaluate(element => element.classList.contains('no-drop'))).toBe(false)

  const pageDrawer = page.getByTestId('action-page-drawer')
  await expect(pageDrawer).toHaveClass(/is-open/)
  await expect(page.getByTestId('action-page-drawer-content')).toHaveText('Page drawer content')
  await pageDrawer.locator('.page-drawer-bottom').getByRole('button').click()
  await expect.poll(() => pageDrawer.evaluate(element => element.classList.contains('is-mini'))).toBe(true)
  await expect(page.getByTestId('action-page-wrapper')).toContainText('Wrapped page')
  await expect(page.getByTestId('action-page-content')).toHaveText('Wrapped content')
  await page.getByRole('button', { name: 'Toggle page loading', exact: true }).click()
  await expect(page.getByTestId('action-page-content')).toHaveCount(0)
  await expect(page.getByTestId('action-page-wrapper').locator('.page-wrapper--loading')).toBeVisible()
  await page.getByRole('button', { name: 'Toggle page loading', exact: true }).click()
  await expect(page.getByTestId('action-archived-chip').filter({ hasText: 'Archivováno' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add record', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save record', exact: true }).click()
  await page.getByRole('button', { name: 'Delete directly', exact: true }).click()
  await expect(page.getByTestId('action-counts')).toHaveText('1:0:1')

  await page.getByRole('button', { name: 'Archive record', exact: true }).click()
  await expect(page.locator('[data-cy="confirm-delete"]')).toBeVisible()
  await page.locator('[data-cy="confirm-delete"]').click()
  await expect(page.getByTestId('action-counts')).toHaveText('1:1:1')
  await expect(page.locator('[data-cy="confirm-delete"]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Delete record', exact: true }).click()
  await expect(page.locator('[data-cy="confirm-delete"]')).toBeVisible()
  await page.locator('[data-cy="confirm-delete"]').click()
  await expect(page.getByTestId('action-counts')).toHaveText('1:1:2')
  await expect(page.locator('[data-cy="confirm-delete"]')).toHaveCount(0)

  await page.getByRole('button', { name: 'Copy record', exact: true }).click()
  await expect(page.getByTestId('action-copy')).toContainText('Zkopírováno')

  await page.getByRole('button', { name: 'Upravit', exact: true }).click()
  await expect(page.getByTestId('editing-model')).toHaveText('true')
  await page.getByRole('button', { name: 'Zrušit', exact: true }).click()
  await expect(page.getByTestId('editing-model')).toHaveText('false')

  const crudGroup = page.getByTestId('crud-group')
  await expect(page.getByTestId('crud-group-prepend')).toHaveText('inline:true')
  await expect(page.getByTestId('crud-group-append')).toHaveText('inline:true')
  await crudGroup.getByRole('button', { name: 'Uložit', exact: true }).click()
  await crudGroup.getByRole('button', { name: 'Archivovat', exact: true }).click()
  await page.locator('[data-cy="confirm-delete"]').click()
  await expect(page.locator('[data-cy="confirm-delete"]')).toHaveCount(0)
  await crudGroup.getByRole('button', { name: 'Smazat', exact: true }).click()
  await expect(page.locator('.menu__content').filter({ hasText: 'Delete from grouped actions?' })).toBeVisible()
  await page.locator('[data-cy="confirm-delete"]').click()
  await expect(page.locator('[data-cy="confirm-delete"]')).toHaveCount(0)
  await page.getByTestId('crud-restore-group').getByRole('button', { name: 'Obnovit', exact: true }).click()
  await page.locator('[data-cy="confirm-delete"]').click()
  await expect(page.getByTestId('crud-group-counts')).toHaveText('1:2:1')

  const drawerTitle = page.locator('.drawer-title[data-testid="action-drawer-title"]')
  await expect(drawerTitle).toContainText('Action drawer')
  await expect(page.getByTestId('action-drawer-left')).toHaveText('left')
  await expect(page.getByTestId('action-drawer-right')).toHaveText('right')
  await drawerTitle.getByRole('button').click()
  await expect(page.getByTestId('action-drawer-open')).toHaveText('false')

  await expect(page.getByTestId('action-draggable')).toHaveText('Draggable action')
  const draggableId = await page.getByTestId('action-draggable')
    .evaluate(element => element['get-item']().id)
  expect(draggableId).toBe('action-item')
  await expect(page.getByTestId('action-data-type')).toBeVisible()
  await expect(page.getByTestId('action-layout-meta').locator('div')).toHaveCount(5)
  await page.getByRole('button', { name: 'Toggle layout meta', exact: true }).click()
  await expect(page.getByTestId('action-layout-meta').locator('div')).toHaveCount(2)

  await page.getByRole('button', { name: 'Open table options', exact: true }).click()
  await expect(page.locator('.dialog').last()).toContainText('Automaticky ukládat rozložení tabulky')
  await page.keyboard.press('Escape')

  await page.getByRole('button', { name: 'Show transient confirmation', exact: true }).click()
  await expect(page.getByText('Saved temporarily', { exact: true })).toBeVisible()
  await expect(page.getByTestId('transient-confirmation-model')).toHaveText('true')

  await page.getByRole('button', { name: 'Toggle owner', exact: true }).click()
  await page.waitForTimeout(2400)
  await expect(page.getByTestId('confirmation-cleanups')).toHaveText('0')
  await page.getByRole('button', { name: 'Toggle owner', exact: true }).click()
  await expect(page.getByTestId('action-counts')).toHaveText('1:1:2')
  await expect(page.getByTestId('action-drawer-open')).toHaveText('false')
  await expect(page.getByTestId('transient-confirmation-model')).toHaveText('false')
  await expect(page.getByTestId('crud-group-counts')).toHaveText('1:2:1')
  expect(problems).toEqual([])
})

test('action primitives and localized navigation render during SSR', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, javaScriptEnabled: false })
  try {
    const page = await context.newPage()
    await page.goto('/cs-CZ/vapor-action-primitives')
    await expect(page.getByTestId('action-drawer-panel')).toHaveClass(/is-open/)
    await expect(page.getByTestId('action-drawer-panel-content')).toHaveText('Drawer content')
    await expect(page.getByTestId('action-draggable-container')).toContainText('First draggable')
    await expect(page.getByTestId('action-draggable-container')).toContainText('Second draggable')
    await expect(page.getByTestId('action-page-drawer')).toHaveClass(/is-open/)
    await expect(page.getByTestId('action-page-drawer-content')).toHaveText('Page drawer content')
    await expect(page.getByTestId('action-page-wrapper')).toContainText('Wrapped page')
    await expect(page.getByTestId('action-page-content')).toHaveText('Wrapped content')
    await expect(page.getByTestId('action-archived-chip').filter({ hasText: 'Archivováno' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Add record', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Save record', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Archive record', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Delete record', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Upravit', exact: true })).toBeVisible()
    await expect(page.getByTestId('crud-group').getByRole('button', { name: 'Uložit', exact: true })).toBeVisible()
    await expect(page.getByTestId('crud-restore-group').getByRole('button', { name: 'Obnovit', exact: true })).toBeVisible()
    await expect(page.getByTestId('action-draggable')).toHaveText('Draggable action')
    await expect(page.getByRole('link', { name: 'Akční prvky · Vapor', exact: true }))
      .toHaveAttribute('href', '/cs-CZ/vapor-action-primitives')
  } finally {
    await context.close()
  }
})
