import { expect, test } from '@playwright/test'

test('Menu and Tooltip preserve declaration anchors and clean up retargeted listeners', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => {
    if (message.type() === 'error' || /hydration/i.test(message.text())) {
      errors.push(message.text())
    }
  })
  await page.goto('/vapor-overlay-anchors')
  await expect(page.getByTestId('overlay-anchors')).toHaveAttribute('data-ready', 'true')
  const a = page.getByRole('button', { name: 'Menu A', exact: true })
  const b = page.getByRole('button', { name: 'Menu B', exact: true })
  const menu = page.getByTestId('anchored-menu')
  const close = async () => {
    await page.getByRole('button', { name: 'Close menu', exact: true }).click()
    await expect(menu).toHaveCount(0)
  }
  await a.click()
  await expect(menu).toBeVisible()
  await close()
  await expect(page.getByTestId('menu-hides')).toHaveText('1')
  await page.getByRole('button', { name: 'Retarget menu' }).click()
  await a.click()
  await expect(menu).toHaveCount(0)
  await b.click()
  await expect(menu).toBeVisible()
  await close()
  await page.getByRole('button', { name: 'Change menu event' }).click()
  await b.click()
  await expect(menu).toHaveCount(0)
  await b.dispatchEvent('contextmenu')
  await expect(menu).toBeVisible()
  await close()
  await page.getByRole('button', { name: 'Toggle menu manual' }).click()
  await b.dispatchEvent('contextmenu')
  await expect(menu).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle menu manual' }).click()
  await page.getByRole('button', { name: 'Toggle menu owner' }).click()
  await b.dispatchEvent('contextmenu')
  await expect(page.getByTestId('menu-model')).toHaveText('false')
  await page.getByRole('button', { name: 'Toggle menu owner' }).click()
  await b.dispatchEvent('contextmenu')
  await expect(menu).toBeVisible()
  await close()
  await expect(page.getByTestId('menu-hides')).toHaveText('4')

  const host = page.getByTestId('tooltip-host')
  const tooltipB = page.getByRole('button', { name: 'Tooltip B', exact: true })
  const tooltip = page.getByTestId('anchored-tooltip')
  await host.dispatchEvent('mouseenter')
  await expect(tooltip).toBeVisible()
  await host.dispatchEvent('mouseleave')
  await expect(tooltip).toHaveCount(0)
  // Retarget within the delay, then wait beyond it: old scheduled work must cancel.
  await host.dispatchEvent('mouseenter')
  await page.getByRole('button', { name: 'Retarget tooltip' }).click()
  await page.waitForTimeout(200)
  await expect(tooltip).toHaveCount(0)
  await expect(host).not.toHaveClass(/has-tooltip|tooltip-hovered/)
  await tooltipB.dispatchEvent('mouseenter')
  await expect(tooltip).toBeVisible()
  await tooltipB.dispatchEvent('mouseleave')
  await expect(tooltip).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle tooltip manual' }).click()
  await tooltipB.dispatchEvent('mouseenter')
  await page.waitForTimeout(200)
  await expect(tooltip).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle tooltip manual' }).click()
  await tooltipB.dispatchEvent('mouseenter')
  await page.getByRole('button', { name: 'Toggle tooltip owner' }).click()
  await page.waitForTimeout(200)
  await expect(tooltipB).not.toHaveClass(/has-tooltip|tooltip-hovered/)
  await expect(page.getByTestId('tooltip-model')).toHaveText('false')
  await page.getByRole('button', { name: 'Toggle tooltip owner' }).click()
  await tooltipB.dispatchEvent('mouseenter')
  await expect(tooltip).toBeVisible()
  await tooltipB.dispatchEvent('mouseleave')
  await expect(tooltip).toHaveCount(0)
  expect(errors).toEqual([])
})

test('closed overlay anchors render on the server without exposing content', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ javaScriptEnabled: false, baseURL })
  try {
    const page = await context.newPage()
    const response = await page.goto('/vapor-overlay-anchors')
    expect(response.status()).toBe(200)
    await expect(page.getByTestId('overlay-anchors')).toHaveAttribute('data-ready', 'false')
    await expect(page.getByRole('button', { name: 'Menu A', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Tooltip A', exact: true })).toBeVisible()
    await expect(page.getByTestId('anchored-menu')).toHaveCount(0)
    await expect(page.getByTestId('anchored-tooltip')).toHaveCount(0)
  } finally {
    await context.close()
  }
})
