import { expect, test } from '@playwright/test'

test('TextInput preserves slots, password visibility, events and public input methods', async ({ page }) => {
  const problems = []
  page.on('pageerror', error => problems.push(error.message))
  page.on('console', message => {
    if (/hydration|no active component/i.test(message.text())) {
      problems.push(message.text())
    }
  })
  await page.goto('/cs-CZ/vapor-text-input')
  await expect(page.getByTestId('text-input-example')).toHaveAttribute('data-ready', 'true')
  const field = page.getByTestId('text-input-field')
  const input = field.locator('input')
  const value = page.getByTestId('text-input-value')
  await expect(input).toHaveValue('initial')
  await input.hover()
  await expect(input).toHaveCSS('cursor', 'text')
  await expect(field).toContainText('Text hint')
  await field.locator('label').click()
  await expect(input).toBeFocused()
  await expect(input).toHaveCSS('cursor', 'text')
  await expect(page.getByText('Text tooltip', { exact: true })).toBeVisible()
  await input.fill('changed')
  await expect(value).toHaveText('changed')
  await input.press('Enter')
  await expect(page.getByTestId('text-input-events')).toHaveText('1 / 0')
  await page.getByRole('button', { name: 'Select input', exact: true }).click()
  expect(await input.evaluate(el => [el.selectionStart, el.selectionEnd])).toEqual([0, 7])
  await page.getByRole('button', { name: 'Blur input', exact: true }).click()
  await expect(input).not.toBeFocused()
  await expect(page.getByText('Text tooltip', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: 'Toggle password', exact: true }).click()
  await expect(input).toHaveAttribute('type', 'password')
  await field.locator('button').first().click()
  await expect(input).toHaveAttribute('type', 'text')
  await expect(input).toHaveValue('changed')
  await page.getByRole('button', { name: 'Toggle password', exact: true }).click()
  await page.getByRole('button', { name: 'Toggle slots', exact: true }).click()
  await expect(field).toContainText('Custom Text')
  await expect(field).toContainText('Custom text hint')
  await field.getByRole('button', { name: 'Slot focus', exact: true }).click()
  await expect(input).toBeFocused()
  await field.getByRole('button', { name: 'Slot clear', exact: true }).click()
  await expect(value).toHaveText('empty')
  await expect(input).toHaveValue('')
  await expect(page.getByTestId('text-input-events')).toHaveText('1 / 1')
  await page.getByRole('button', { name: 'Toggle slots', exact: true }).click()
  await expect(field).not.toContainText('Custom')
  await expect(field).toContainText('Text hint')
  await page.getByRole('button', { name: 'Replace model', exact: true }).click()
  await expect(input).toHaveValue('replacement')
  await page.getByRole('button', { name: 'Toggle readonly', exact: true }).click()
  await expect(input).toHaveAttribute('readonly', '')
  await expect(input).toHaveCSS('cursor', 'default')
  await page.getByRole('button', { name: 'Toggle readonly', exact: true }).click()
  await page.getByRole('button', { name: 'Toggle owner', exact: true }).click()
  await expect(input).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle owner', exact: true }).click()
  await page.getByRole('button', { name: 'Focus input', exact: true }).click()
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('replacement')
  expect(problems).toEqual([])
})

test('TextInput renders fallback label, hint and localized navigation without JavaScript', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, javaScriptEnabled: false })
  try {
    const page = await context.newPage()
    await page.goto('/cs-CZ/vapor-text-input')
    const field = page.getByTestId('text-input-field')
    await expect(field.locator('input')).toHaveValue('initial')
    await expect(field.locator('input')).toHaveAttribute('placeholder', 'Text value')
    await expect(field.locator('label')).toContainText('Text')
    await expect(field).toContainText('Text hint')
    await expect(page.getByText('Text tooltip', { exact: true })).not.toBeVisible()
    await expect(page.getByRole('link', { name: 'TextInput · sloty, heslo a focus', exact: true }))
      .toHaveAttribute('href', '/cs-CZ/vapor-text-input')
  } finally {
    await context.close()
  }
})
