import { expect, test } from '@playwright/test'

test('presentation primitives update, switch variants and remount without renderer errors', async ({ page }) => {
  const problems = []
  page.on('pageerror', error => problems.push(error.message))
  page.on('console', message => {
    if (/hydration|no active component/i.test(message.text())) {
      problems.push(message.text())
    }
  })

  await page.goto('/cs-CZ/vapor-presentation-primitives')
  const example = page.getByTestId('presentation-primitives-example')
  await expect(example).toHaveAttribute('data-ready', 'true')

  await expect(page.getByTestId('presentation-navigation')).toHaveClass(/is-sticky/)
  await expect(page.getByTestId('navigation-content')).toHaveText('Navigation content')
  await expect(page.getByTestId('presentation-main-bar')).toContainText('Presentation main bar')
  await expect(page.getByTestId('presentation-main-bar')).toContainText('Main bar subtitle')
  await expect(page.getByTestId('main-bar-left')).toHaveText('Left')
  await expect(page.getByTestId('main-bar-title-append')).toHaveText('Append')
  await expect(page.getByTestId('main-bar-right')).toHaveText('Right')
  await expect(page.getByTestId('main-bar-inner')).toHaveText('Inner')
  await expect(page.getByTestId('presentation-breadcrumbs').getByRole('link', { name: 'Library', exact: true }))
    .toHaveAttribute('href', '/library')
  await expect(page.getByTestId('presentation-breadcrumbs')).toContainText('Current page')
  await expect(page.getByTestId('breadcrumbs-append')).toHaveText('Append')
  await expect(page.getByTestId('breadcrumbs-right')).toHaveText('Right')
  await expect(page.getByTestId('presentation-banner')).toContainText('Banner content')
  await expect(page.getByTestId('presentation-banner').locator('.badge')).toHaveText('1')
  await expect(page.getByTestId('presentation-section')).toContainText('Presentation section')
  await expect(page.getByTestId('presentation-section')).toContainText('Section subtitle')
  await expect(page.getByTestId('section-content')).toHaveText('Section content')
  await expect(page.getByTestId('presentation-section').locator('.skeleton')).toHaveCount(0)
  await expect(page.getByTestId('presentation-page-title')).toContainText('BeforePresentation titleAfter')
  await expect(page.getByTestId('page-title-below')).toHaveText('Below')
  await expect(page.getByTestId('presentation-collapse')).toHaveAttribute('data-state', 'closed')
  await expect(page.getByTestId('collapse-content')).not.toBeVisible()
  await page.getByTestId('presentation-collapse').locator('.collapse__header').click()
  await expect(page.getByTestId('presentation-collapse')).toHaveAttribute('data-state', 'open')
  await expect(page.getByTestId('collapse-content')).toBeVisible()
  await expect(page.getByTestId('presentation-heading')).toHaveText('Presentation primitives')
  await expect(page.getByTestId('presentation-heading')).toHaveCSS('min-height', '32px')
  await expect(page.getByTestId('formatted-field')).toContainText('field-value')
  await expect(page.getByTestId('formatted-append')).toHaveText('append')
  await expect(page.getByTestId('formatted-current')).toHaveText('formatted:current')
  await expect(page.getByTestId('formatted-previous')).toHaveText('formatted:previous')
  await expect(page.getByTestId('presentation-separator')).toHaveClass(/is-horizontal/)
  await expect(page.getByTestId('presentation-skeleton')).toHaveClass(/variant--wave/)
  await expect(page.getByTestId('presentation-loader')).toHaveAttribute('id', 'L7')
  await expect(page.getByTestId('presentation-loader-block')).toHaveClass(/h-6/)
  await expect(page.getByTestId('presentation-loader-inline')).toHaveClass(/h-6/)
  await expect(page.getByTestId('presentation-progress')).toContainText('Loaded 25%')
  const progressBar = page.getByTestId('presentation-progress')
  const progressFill = progressBar.locator('.progress-bar__black')
  const progressRatio = await progressFill.evaluate(fill => {
    const container = fill.parentElement

    return fill.getBoundingClientRect().width / (container?.getBoundingClientRect().width ?? 1)
  })
  expect(progressRatio).toBeCloseTo(0.25, 2)
  await expect(page.getByTestId('presentation-circle')).toContainText('25%')
  await expect(page.getByTestId('presentation-circle').locator('.circle-progress__circle'))
    .toHaveAttribute('stroke-dasharray', '25, 100')
  await expect(page.getByTestId('circle-slot')).toHaveText('slot')

  await page.getByRole('button', { name: 'Increment banner', exact: true }).click()
  await expect(page.getByTestId('presentation-banner').locator('.badge')).toHaveText('2')
  await page.getByTestId('presentation-banner').click()
  await expect(page.getByTestId('presentation-banner')).toHaveCount(0)
  await page.getByRole('button', { name: 'Show banner', exact: true }).click()
  await expect(page.getByTestId('presentation-banner')).toContainText('Banner content')
  await page.getByRole('button', { name: 'Toggle section loading', exact: true }).click()
  await expect(page.getByTestId('presentation-section').locator('.skeleton')).toBeVisible()
  await page.getByRole('button', { name: 'Change progress', exact: true }).click()
  await expect(page.getByTestId('presentation-progress')).toContainText('Loaded 70%')
  await expect(page.getByTestId('presentation-circle')).toContainText('70%')

  await page.getByRole('button', { name: 'Toggle separator', exact: true }).click()
  await expect(page.getByTestId('presentation-separator')).toHaveClass(/is-vertical/)
  await page.getByLabel('Skeleton variant', { exact: true }).selectOption('blink')
  await expect(page.getByTestId('presentation-skeleton')).toHaveClass(/variant--blink/)
  await page.getByLabel('Loader variant', { exact: true }).selectOption('inline')
  await expect(page.getByTestId('presentation-loader')).toHaveAttribute('id', 'L4')

  await page.getByRole('button', { name: 'Toggle owner', exact: true }).click()
  await expect(page.getByTestId('presentation-owner')).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle owner', exact: true }).click()
  await expect(page.getByTestId('presentation-progress')).toContainText('Loaded 70%')
  await expect(page.getByTestId('presentation-banner').locator('.badge')).toHaveText('2')
  await expect(page.getByTestId('presentation-section').locator('.skeleton')).toBeVisible()
  await expect(page.getByTestId('presentation-skeleton')).toHaveClass(/variant--blink/)
  await expect(page.getByTestId('presentation-collapse')).toHaveAttribute('data-state', 'open')
  await page.getByTestId('presentation-collapse').locator('.collapse__header').click()
  await expect(page.getByTestId('collapse-content')).not.toBeVisible()
  expect(problems).toEqual([])
})

test('presentation primitives and localized navigation render during SSR', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, javaScriptEnabled: false })
  try {
    const page = await context.newPage()
    await page.goto('/cs-CZ/vapor-presentation-primitives')
    await expect(page.getByTestId('presentation-navigation')).toHaveClass(/is-sticky/)
    await expect(page.getByTestId('navigation-content')).toHaveText('Navigation content')
    await expect(page.getByTestId('presentation-main-bar')).toContainText('Presentation main bar')
    await expect(page.getByTestId('main-bar-left')).toHaveText('Left')
    await expect(page.getByTestId('main-bar-right')).toHaveText('Right')
    await expect(page.getByTestId('presentation-breadcrumbs')).toContainText('Library')
    await expect(page.getByTestId('breadcrumbs-append')).toHaveText('Append')
    await expect(page.getByTestId('presentation-banner')).toContainText('Banner content')
    await expect(page.getByTestId('presentation-banner').locator('.badge')).toHaveText('1')
    await expect(page.getByTestId('presentation-section')).toContainText('Presentation section')
    await expect(page.getByTestId('section-content')).toHaveText('Section content')
    await expect(page.getByTestId('presentation-page-title')).toContainText('Presentation title')
    await expect(page.getByTestId('presentation-collapse')).toHaveAttribute('data-state', 'closed')
    await expect(page.getByTestId('collapse-content')).not.toBeVisible()
    await expect(page.getByTestId('presentation-heading')).toHaveText('Presentation primitives')
    await expect(page.getByTestId('formatted-field')).toContainText('field-value')
    await expect(page.getByTestId('formatted-current')).toHaveText('formatted:current')
    await expect(page.getByTestId('presentation-progress')).toContainText('Loaded 25%')
    await expect(page.getByTestId('presentation-circle')).toContainText('25%')
    await expect(page.getByRole('link', { name: 'Prezentační prvky · Vapor', exact: true }))
      .toHaveAttribute('href', '/cs-CZ/vapor-presentation-primitives')
  } finally {
    await context.close()
  }
})
