import { expect, test } from '@playwright/test'

test('control primitives preserve models, slots, DOM properties and remount', async ({ page }) => {
  const problems = []
  page.on('pageerror', error => problems.push(error.message))
  page.on('console', message => {
    if (/hydration|no active component/i.test(message.text())) {
      problems.push(message.text())
    }
  })

  await page.goto('/cs-CZ/vapor-control-primitives')
  await expect(page.getByTestId('control-primitives-example')).toHaveAttribute('data-ready', 'true')

  const checkbox = page.getByTestId('state-checkbox')
  const checkboxInput = checkbox.locator('input')
  await expect(page.getByTestId('checkbox-model')).toHaveText('false')
  await expect(checkbox).toContainText('Checkbox: false')
  await expect(page.getByTestId('checkbox-append')).toHaveText('checkbox append')
  await expect(checkboxInput).not.toBeChecked()
  await expect(checkboxInput).toHaveJSProperty('indeterminate', false)
  await checkbox.click()
  await expect(page.getByTestId('checkbox-model')).toHaveText('null')
  await expect(checkboxInput).toHaveJSProperty('indeterminate', true)
  await checkbox.press('Space')
  await expect(page.getByTestId('checkbox-model')).toHaveText('true')
  await expect(checkboxInput).toBeChecked()
  await expect(checkboxInput).toHaveJSProperty('indeterminate', false)
  await page.getByRole('button', { name: 'Focus checkbox', exact: true }).click()
  await expect(checkbox).toBeFocused()

  await page.getByTestId('array-checkbox-beta').click()
  await expect(page.getByTestId('checkbox-array-model')).toHaveText('alpha,beta')
  await page.getByTestId('array-checkbox-alpha').click()
  await expect(page.getByTestId('checkbox-array-model')).toHaveText('beta')
  await page.getByTestId('readonly-checkbox').click()
  await expect(page.getByTestId('readonly-checkbox-model')).toHaveText('false')

  const toggle = page.getByTestId('state-toggle')
  await expect(toggle).toHaveClass(/is-unchecked/)
  await expect(toggle).toContainText('Toggle: unchecked')
  await expect(page.getByTestId('toggle-prepend')).toHaveText('toggle prepend')
  await expect(page.getByTestId('toggle-bullet')).toHaveText('bullet')
  await expect(page.getByTestId('toggle-append')).toHaveText('toggle append')
  await toggle.click()
  await expect(page.getByTestId('toggle-model')).toHaveText('null')
  await expect(toggle).toHaveClass(/is-indeterminate/)
  await toggle.press('Enter')
  await expect(page.getByTestId('toggle-model')).toHaveText('true')
  await expect(toggle).toHaveClass(/is-checked/)
  await page.getByRole('button', { name: 'Focus toggle', exact: true }).click()
  await expect(toggle).toBeFocused()

  const stringToggle = page.getByTestId('string-toggle')
  await expect(stringToggle).toHaveClass(/is-checked/)
  await stringToggle.click()
  await expect(page.getByTestId('string-toggle-model')).toHaveText('false')
  await page.getByTestId('readonly-toggle').click()
  await expect(page.getByTestId('readonly-toggle-model')).toHaveText('false')

  const queryBoolean = page.getByTestId('query-boolean')
  await expect(page.getByTestId('query-boolean-state')).toHaveText('true:0')
  await queryBoolean.getByRole('button').nth(1).click()
  await expect(page.getByTestId('query-boolean-state')).toHaveText('false:0')
  await queryBoolean.getByRole('button').first().click()
  await expect(page.getByTestId('query-boolean-state')).toHaveText('true:0')
  await queryBoolean.getByRole('button').nth(2).click()
  await expect(page.getByTestId('query-boolean-state')).toHaveText('true:1')
  await expect(page.getByTestId('query-move-handler')).toBeVisible()

  await page.getByRole('button', { name: 'Open confirmation', exact: true }).click()
  await expect(page.getByTestId('confirmation-checkmark')).toHaveText('custom checkmark')
  await expect(page.getByTestId('confirmation-content')).toHaveText('Custom confirmation content')
  await expect(page.getByTestId('confirmation-actions')).toHaveText('custom action')
  await page.getByRole('button', { name: 'Zavřít', exact: true }).click()
  await expect(page.getByTestId('confirmation-state')).toHaveText('false:1')
  await expect(page.getByTestId('confirmation-content')).toHaveCount(0)

  const marquee = page.getByTestId('state-marquee')
  await expect(marquee.getByTestId('marquee-content')).toHaveCount(2)
  await expect(marquee).toHaveCSS('--duration', '12s')
  await expect(marquee).toHaveCSS('--gap', '7px')
  await page.getByRole('button', { name: 'Toggle marquee vertical', exact: true }).click()
  await expect(marquee).toHaveClass(/is-vertical/)
  await expect(marquee.locator('.animate-marquee-vertical')).toHaveCount(2)
  await page.getByRole('button', { name: 'Toggle marquee reverse', exact: true }).click()
  await expect(marquee.locator('.animate-marquee-vertical').first()).toHaveCSS('animation-direction', 'reverse')
  await page.getByRole('button', { name: 'Add marquee track', exact: true }).click()
  await expect(marquee.getByTestId('marquee-content')).toHaveCount(3)

  await page.getByRole('button', { name: 'Toggle owner', exact: true }).click()
  await expect(page.getByTestId('control-primitives-owner')).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle owner', exact: true }).click()
  await expect(page.getByTestId('checkbox-model')).toHaveText('true')
  await expect(page.getByTestId('toggle-model')).toHaveText('true')
  await expect(page.getByTestId('string-toggle-model')).toHaveText('false')
  await expect(page.getByTestId('query-boolean-state')).toHaveText('true:1')
  await expect(page.getByTestId('confirmation-state')).toHaveText('false:1')
  await expect(page.getByTestId('state-marquee').getByTestId('marquee-content')).toHaveCount(3)
  expect(problems).toEqual([])
})

test('control primitives and localized navigation render during SSR', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, javaScriptEnabled: false })
  try {
    const page = await context.newPage()
    await page.goto('/cs-CZ/vapor-control-primitives')
    await expect(page.getByTestId('state-checkbox')).toContainText('Checkbox: false')
    await expect(page.getByTestId('checkbox-append')).toHaveText('checkbox append')
    await expect(page.getByTestId('state-toggle')).toContainText('Toggle: unchecked')
    await expect(page.getByTestId('toggle-bullet')).toHaveText('bullet')
    await expect(page.getByTestId('query-boolean-state')).toHaveText('true:0')
    await expect(page.getByTestId('query-move-handler')).toBeVisible()
    await expect(page.getByTestId('confirmation-content')).toHaveCount(0)
    await expect(page.getByTestId('state-marquee').getByTestId('marquee-content')).toHaveCount(2)
    await expect(page.getByRole('link', { name: 'Ovládací prvky · Vapor', exact: true }))
      .toHaveAttribute('href', '/cs-CZ/vapor-control-primitives')
  } finally {
    await context.close()
  }
})
