import { expect, test } from '@playwright/test'

test('virtual rows measure growth and shrink without affecting another scroller', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => {
    if (/hydration.*mismatch/i.test(message.text())) {
      errors.push(message.text())
    }
  })
  await page.goto('/cs-CZ/vapor-virtual-scroller')
  await expect(page.getByTestId('virtual-example')).toHaveAttribute('data-ready', 'true')
  const primary = page.getByTestId('primary-scroller')
  const secondary = page.getByTestId('secondary-scroller')
  const row = (scroller, id) => scroller.locator(`.virtual-scroll__row[data-key="${id}"]`)
  await expect(primary).toHaveClass(/is-virtual/)
  await expect.poll(() => primary.locator('.virtual-scroll__row').count()).toBeLessThan(30)
  await expect(row(primary, 0)).toHaveCSS('height', '32px')
  await page.getByRole('button', { name: 'Toggle heights', exact: true }).click()
  await expect(row(primary, 0)).toHaveCSS('height', '112px')
  await expect.poll(() => row(primary, 1).evaluate(el => el.getBoundingClientRect().top - el.previousElementSibling.getBoundingClientRect().bottom)).toBe(0)
  await expect(row(secondary, 0)).toHaveCSS('height', '32px')
  await expect(row(secondary, 1)).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 32)')
  await page.getByRole('button', { name: 'Toggle heights', exact: true }).click()
  await expect(row(primary, 0)).toHaveCSS('height', '32px')
  await expect(row(primary, 1)).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 32)')

  await page.getByRole('button', { name: 'Scroll to row 60', exact: true }).click()
  await expect(row(primary, 60)).toBeVisible()
  await expect.poll(async () => Number(await page.getByTestId('start-index').textContent())).toBeGreaterThan(55)
  await page.getByRole('button', { name: 'Render viewport only', exact: true }).click()
  await expect.poll(async () => Number(await page.getByTestId('visible-result').textContent())).toBe(60)
  await expect(row(primary, 0)).toHaveCount(0)
  await page.getByRole('button', { name: 'Clear rendered rows', exact: true }).click()
  await expect(primary.locator('.virtual-scroll__row')).toHaveCount(0)
  await page.getByRole('button', { name: 'Rerender rows', exact: true }).click()
  await expect(row(primary, 60)).toBeVisible()
  await page.getByRole('button', { name: 'Toggle heights', exact: true }).click()
  await expect(row(primary, 60)).toHaveCSS('height', '112px')
  await expect.poll(() => row(primary, 61).evaluate(el => el.getBoundingClientRect().top - el.previousElementSibling.getBoundingClientRect().bottom)).toBe(0)
  await expect(row(secondary, 1)).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 32)')
  await page.getByRole('button', { name: 'Append rows', exact: true }).click()
  await page.getByRole('button', { name: 'Scroll to bottom', exact: true }).click()
  await expect(row(primary, 119)).toBeVisible()
  await page.getByRole('button', { name: 'Clear data', exact: true }).click()
  await expect(primary.locator('.virtual-scroll__row')).toHaveCount(0)
  await expect(primary.locator('.virtual-scroll__content')).toHaveCSS('min-height', '0px')
  await page.getByRole('button', { name: 'Append rows', exact: true }).click()
  await page.getByRole('button', { name: 'Scroll to top', exact: true }).click()
  await expect(row(primary, 0)).toBeVisible()
  await page.getByRole('button', { name: 'Toggle virtual owner', exact: true }).click()
  await expect(primary).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle heights', exact: true }).click()
  await page.getByRole('button', { name: 'Toggle virtual owner', exact: true }).click()
  await expect(row(primary, 0)).toHaveCSS('height', '32px')
  expect(errors).toEqual([])
})

test('virtual scroller SSR and small-list fallback preserve slots and navigation', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, javaScriptEnabled: false })
  try {
    const page = await context.newPage()
    await page.goto('/cs-CZ/vapor-virtual-scroller?small=true')
    await expect(page.getByTestId('primary-scroller').locator('.virtual-scroll__row')).toHaveCount(6)
    await expect(page.getByTestId('inner-content')).toHaveText('Inner content')
    await expect(page.getByRole('link', { name: 'VirtualScroller · bez virtualizace', exact: true }))
      .toHaveAttribute('href', '/cs-CZ/vapor-virtual-scroller?small=true')
    await page.goto('/cs-CZ/vapor-virtual-scroller')
    await expect(page.getByTestId('primary-scroller').locator('.virtual-scroll__row')).toHaveCount(8)
    await expect(page.getByRole('link', { name: 'VirtualScroller · měření řádků', exact: true }))
      .toHaveAttribute('href', '/cs-CZ/vapor-virtual-scroller')
  } finally {
    await context.close()
  }
})
