import { expect, test } from '@playwright/test'

test('TextArea preserves slots, autogrow, events and public input methods', async ({ page }) => {
  const problems = []
  page.on('pageerror', error => problems.push(error.message))
  page.on('console', message => {
    if (/hydration|no active component/i.test(message.text())) {
      problems.push(message.text())
    }
  })
  await page.goto('/cs-CZ/vapor-text-area')
  await expect(page.getByTestId('text-area-example')).toHaveAttribute('data-ready', 'true')
  const field = page.getByTestId('text-area-field')
  const input = field.locator('textarea')
  const value = page.getByTestId('text-area-value')
  await expect(input).toHaveValue('initial')
  await input.hover()
  await expect(input).toHaveCSS('cursor', 'text')
  await expect(field).toContainText('Area hint')
  await field.locator('label').click()
  await expect(input).toBeFocused()
  await expect(input).toHaveCSS('cursor', 'text')
  await expect(page.getByText('Area tooltip', { exact: true })).toBeVisible()
  const initialHeight = (await input.boundingBox()).height
  await input.fill('one\ntwo\nthree\nfour\nfive\nsix')
  await expect.poll(async () => (await input.boundingBox()).height).toBeGreaterThan(initialHeight)
  await expect(input).toHaveCSS('resize', 'none')
  await input.fill('changed')
  await expect.poll(async () => (await input.boundingBox()).height).toBeLessThan(initialHeight + 2)
  await expect(value).toHaveText('changed')
  await page.getByRole('button', { name: 'Select input', exact: true }).click()
  expect(await input.evaluate(el => [el.selectionStart, el.selectionEnd])).toEqual([0, 7])
  await page.getByRole('button', { name: 'Blur input', exact: true }).click()
  await expect(input).not.toBeFocused()
  await expect(page.getByText('Area tooltip', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: 'Toggle slots', exact: true }).click()
  await expect(field).toContainText('Custom Area')
  await expect(field).toContainText('Custom area hint')
  await expect(page.getByTestId('area-inner')).toBeVisible()
  await expect(page.getByTestId('area-menu')).toBeVisible()
  await field.getByRole('button', { name: 'Slot focus', exact: true }).click()
  await expect(input).toBeFocused()
  await field.getByRole('button', { name: 'Slot clear', exact: true }).click()
  await expect(value).toHaveText('empty')
  await expect(input).toHaveValue('')
  await expect(page.getByTestId('text-area-events')).toHaveText('1')
  await page.getByRole('button', { name: 'Toggle slots', exact: true }).click()
  await expect(field).not.toContainText('Custom')
  await expect(page.getByTestId('area-inner')).toHaveCount(0)
  await expect(page.getByTestId('area-menu')).toHaveCount(0)
  await expect(field).toContainText('Area hint')
  await page.getByRole('button', { name: 'Replace model', exact: true }).click()
  await expect(input).toHaveValue('replacement')
  await page.getByRole('button', { name: 'Toggle readonly', exact: true }).click()
  await expect(input).toHaveAttribute('readonly', '')
  await expect(input).toHaveCSS('cursor', 'default')
  await page.getByRole('button', { name: 'Toggle readonly', exact: true }).click()
  await page.getByRole('button', { name: 'Toggle owner', exact: true }).click()
  await expect(input).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle owner', exact: true }).click()
  await page.getByRole('button', { name: 'Focus input', exact: true }).click()
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('replacement')
  await page.getByRole('button', { name: 'Update mask', exact: true }).click()
  await expect(input).toHaveValue('mask edit')
  await expect(value).toHaveText('mask edit')
  expect(problems).toEqual([])
})

test('TextArea renders fallback label, hint and localized navigation without JavaScript', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, javaScriptEnabled: false })
  try {
    const page = await context.newPage()
    await page.goto('/cs-CZ/vapor-text-area')
    const field = page.getByTestId('text-area-field')
    await expect(field.locator('textarea')).toHaveValue('initial')
    await expect(field.locator('textarea')).toHaveAttribute('placeholder', 'Area value')
    await expect(field.locator('label')).toContainText('Area')
    await expect(field).toContainText('Area hint')
    await expect(page.getByText('Area tooltip', { exact: true })).not.toBeVisible()
    await expect(page.getByRole('link', { name: 'TextArea · autogrow a sloty', exact: true }))
      .toHaveAttribute('href', '/cs-CZ/vapor-text-area')
  } finally {
    await context.close()
  }
})

test('TextArea retains fixed rows when autogrow is disabled', async ({ page }) => {
  await page.goto('/cs-CZ/vapor-text-area')
  await page.getByRole('link', { name: 'TextArea · pevné řádky', exact: true }).click()
  await expect(page).toHaveURL(/autogrow=false/)
  await expect(page.getByTestId('text-area-example')).toHaveAttribute('data-ready', 'true')
  const input = page.getByTestId('text-area-field').locator('textarea')
  const initialHeight = (await input.boundingBox()).height
  await expect(input).toHaveAttribute('rows', '3')
  await expect(input).toHaveCSS('resize', 'vertical')
  await input.fill('one\ntwo\nthree\nfour\nfive\nsix')
  await expect.poll(async () => (await input.boundingBox()).height).toBe(initialHeight)
  await expect(page.getByRole('link', { name: 'TextArea · pevné řádky', exact: true }))
    .toHaveAttribute('href', '/cs-CZ/vapor-text-area?autogrow=false')
})
