//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                createdById: {
                    name: "createdById",
                    type: "Int",
                    optional: true
                },
                createdByUserId: {
                    name: "createdByUserId",
                    type: "Int",
                    optional: true
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    optional: true,
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                updatedById: {
                    name: "updatedById",
                    type: "Int",
                    optional: true
                },
                updatedByUserId: {
                    name: "updatedByUserId",
                    type: "Int",
                    optional: true
                },
                deleted: {
                    name: "deleted",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true
                },
                deletedById: {
                    name: "deletedById",
                    type: "Int",
                    optional: true
                },
                deletedByUserId: {
                    name: "deletedByUserId",
                    type: "Int",
                    optional: true
                },
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }, { name: "@email" }, { name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(6) }, { name: "max", value: ExpressionUtils.literal(32) }] }]
                },
                password: {
                    name: "password",
                    type: "String",
                    attributes: [{ name: "@password", args: [{ name: "hasher", value: ExpressionUtils.call("bcryptHasher", [ExpressionUtils.literal(10)]) }] }]
                },
                type: {
                    name: "type",
                    type: "UserType"
                },
                posts: {
                    name: "posts",
                    type: "Post",
                    array: true,
                    relation: { opposite: "author" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Post: {
            name: "Post",
            fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                createdById: {
                    name: "createdById",
                    type: "Int",
                    optional: true
                },
                createdByUserId: {
                    name: "createdByUserId",
                    type: "Int",
                    optional: true
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    optional: true,
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                updatedById: {
                    name: "updatedById",
                    type: "Int",
                    optional: true
                },
                updatedByUserId: {
                    name: "updatedByUserId",
                    type: "Int",
                    optional: true
                },
                deleted: {
                    name: "deleted",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true
                },
                deletedById: {
                    name: "deletedById",
                    type: "Int",
                    optional: true
                },
                deletedByUserId: {
                    name: "deletedByUserId",
                    type: "Int",
                    optional: true
                },
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                title: {
                    name: "title",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(256) }] }]
                },
                content: {
                    name: "content",
                    type: "String"
                },
                published: {
                    name: "published",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                authorId: {
                    name: "authorId",
                    type: "String",
                    foreignKeyFor: [
                        "author"
                    ]
                },
                author: {
                    name: "author",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("authorId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "posts", fields: ["authorId"], references: ["id"] }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        Timestamps: {
            name: "Timestamps",
            fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                createdById: {
                    name: "createdById",
                    type: "Int",
                    optional: true
                },
                createdByUserId: {
                    name: "createdByUserId",
                    type: "Int",
                    optional: true
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    optional: true,
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                updatedById: {
                    name: "updatedById",
                    type: "Int",
                    optional: true
                },
                updatedByUserId: {
                    name: "updatedByUserId",
                    type: "Int",
                    optional: true
                },
                deleted: {
                    name: "deleted",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                deletedAt: {
                    name: "deletedAt",
                    type: "DateTime",
                    optional: true
                },
                deletedById: {
                    name: "deletedById",
                    type: "Int",
                    optional: true
                },
                deletedByUserId: {
                    name: "deletedByUserId",
                    type: "Int",
                    optional: true
                }
            }
        }
    } as const;
    enums = {
        UserType: {
            values: {
                ADMIN: "ADMIN",
                USER: "USER"
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
